### PR TITLE
feat: assignments

### PR DESCRIPTION
**Pull request by milogert**
Found at https://api.live.prod.thehelldiversgame.com/api/v2/Assignment/War/801

How I ran into this, I have no idea.

This is a _ROUGH_ change, that I'm happy to get feedback on. I basically copied patterns that already existed.

Additionally I added some Nix-related things. I have found developing Elixir with Nix to be a great experience. I copied the files from another project so there might be extraneous stuff in there.

TODO
---

- [x] The schema stuff for Swagger, completely not done.
- [ ] Tests
- [x] Elixir versions in Nix

### CODE REVIEW

**Comment by dealloc** [comment]
hi @milogert great to have your contribution here!
I'll be checking this out ASAP when I have the chance, the one thing I'm not too keen on is the addition of Nix as I have no experience with this so I'm not entirely comfortable reviewing Nix related code :)

**Comment by milogert** [comment]
Thanks for looking at this!

As for the Nix stuff, it should be viewed like the `.vscode` directory in repositories. Basically this code I added is _just_ a dev-related change, so it can be ignored be ignored by people who don't have Nix installed. The big exception is if you bump the Elixir version then the version in the `shell.nix` file should be bumped as well.

All that being said, I'd be happy to maintain that part of the code or whatever! If you ever get any bugs related to it (or bump the Elixir version) feel free to assign me to it and I'd love to take a look. Chances are someone just ran into the bug before me

**Comment by dealloc** [comment]
I'm going to keep this open until #28 gives a little more clarification on the direction we're taking with this project

**Comment by dealloc** [comment]
hi @milogert, while I really appreciate the contribution I'm afraid I'm going to have to close this in favour of #30 as discussed in #28

I hope to see more contributions from you going forward :)

**Pull request closed without merging**
